name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t multi-docker -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true multi-docker npm test

      - run: docker build -t multi-client ./client
      - run: docker build -t multi-nginx ./nginx
      - run: docker build -t multi-server ./server
      - run: docker build -t multi-worker ./worker

      - run: docker push multi-client
      - run: docker push multi-nginx
      - run: docker push multi-server
      - run: docker push multi-worker
